#!/usr/bin/env python3
"""
Import MedQuAD Neo4j CSV files into a running Neo4j database.

CSV formats (generated by prepare_neo4j_medquad.py):

Nodes:
- nodes_questions.csv:
    question_id, question, answer, source, focus_area
- nodes_diseases.csv:
    disease
- nodes_chemicals.csv:
    chemical

Relationships:
- rels_question_disease.csv:
    question_id, disease
- rels_question_chemical.csv:
    question_id, chemical
"""

import csv
from neo4j import GraphDatabase

URI = "neo4j://localhost:7687"
USER = "neo4j"
PASSWORD = "Anvesh@01"

CSV_DIR = "data/neo4j"


class MedQuadImporter:
    def __init__(self):
        self.driver = GraphDatabase.driver(URI, auth=(USER, PASSWORD))

    def close(self):
        self.driver.close()

    def run_query(self, query, params=None):
        with self.driver.session() as session:
            session.run(query, params or {})

    def create_constraints(self):
        print("Creating constraints...")

        queries = [
            "CREATE CONSTRAINT IF NOT EXISTS FOR (q:Question) REQUIRE q.question_id IS UNIQUE",
            "CREATE CONSTRAINT IF NOT EXISTS FOR (d:Disease) REQUIRE d.name IS UNIQUE",
            "CREATE CONSTRAINT IF NOT EXISTS FOR (c:Chemical) REQUIRE c.name IS UNIQUE",
        ]

        for q in queries:
            self.run_query(q)

        print("Constraints created.")

    def import_questions(self):
        print("Importing Question nodes...")

        with open(f"{CSV_DIR}/nodes_questions.csv", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                params = {
                    "question_id": row["question_id"],
                    "question": row["question"],
                    "answer": row["answer"],
                    "source": row["source"],
                    "focus_area": row["focus_area"],
                }
                self.run_query(
                    """
                    MERGE (q:Question {question_id: $question_id})
                    SET q.question = $question,
                        q.answer = $answer,
                        q.source = $source,
                        q.focus_area = $focus_area
                    """,
                    params,
                )

        print("Questions imported.")

    def import_diseases(self):
        print("Importing Disease nodes...")

        with open(f"{CSV_DIR}/nodes_diseases.csv", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                disease = row.get("disease", "").strip()
                if not disease:
                    continue
                self.run_query(
                    "MERGE (d:Disease {name: $disease})",
                    {"disease": disease},
                )

        print("Diseases imported.")

    def import_chemicals(self):
        print("Importing Chemical nodes...")

        with open(f"{CSV_DIR}/nodes_chemicals.csv", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                chemical = row.get("chemical", "").strip()
                if not chemical:
                    continue
                self.run_query(
                    "MERGE (c:Chemical {name: $chemical})",
                    {"chemical": chemical},
                )

        print("Chemicals imported.")

    def import_relationships(self):
        print("Importing Question–Disease relationships...")

        with open(f"{CSV_DIR}/rels_question_disease.csv", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                qid = row.get("question_id", "").strip()
                disease = row.get("disease", "").strip()
                if not qid or not disease:
                    continue
                self.run_query(
                    """
                    MATCH (q:Question {question_id: $question_id})
                    MATCH (d:Disease {name: $disease})
                    MERGE (q)-[:MENTIONS_DISEASE]->(d)
                    """,
                    {"question_id": qid, "disease": disease},
                )

        print("Importing Question–Chemical relationships...")

        with open(f"{CSV_DIR}/rels_question_chemical.csv", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                qid = row.get("question_id", "").strip()
                chemical = row.get("chemical", "").strip()
                if not qid or not chemical:
                    continue
                self.run_query(
                    """
                    MATCH (q:Question {question_id: $question_id})
                    MATCH (c:Chemical {name: $chemical})
                    MERGE (q)-[:MENTIONS_CHEMICAL]->(c)
                    """,
                    {"question_id": qid, "chemical": chemical},
                )

        print("Relationships imported.")

    def run(self):
        self.create_constraints()
        self.import_questions()
        self.import_diseases()
        self.import_chemicals()
        self.import_relationships()


if __name__ == "__main__":
    importer = MedQuadImporter()
    importer.run()
    importer.close()
    print("\nNeo4j Import Completed.\n")